### PR TITLE
Multi build 1

### PR DESCRIPTION
**Pull request by montjoie**

### CODE REVIEW

**Comment by aliceinwire** [comment]
copy artifacts and build should stay divided for logging reasons.

**Comment by aliceinwire** [comment]
you should change also https://github.com/GKernelCI/Ghelper/blob/f14395e0c95854e710fe7736e5e640d5e61215c1/run_tests.sh#L6 for don't breaking anything

**Comment by aliceinwire** [comment]
You should change also this part https://github.com/GKernelCI/Ghelper/blob/f14395e0c95854e710fe7736e5e640d5e61215c1/run_tests.sh#L62 for don't break anything

**Comment by montjoie** [comment]
I changed only build place, not where on fileserver

**Pull request merged**
