### PR TITLE
License as GPL-2.0-or-later

### PR DESCRIPTION
**Pull request by oxr463**

### CODE REVIEW

**Comment by aliceinwire** [comment]
@spbnick is ok for you ?

**Comment by spbnick** [comment]
Yep, fully compatible with KCIDB's GPLv2 :)

**Comment by aliceinwire** [comment]
@mjeveritt is it ok for you ?

**Comment by mjeveritt** [comment]
> @mjeveritt is it ok for you ?

No objection from me .. I defer to the licensing gurus... :stuck_out_tongue:

**Pull request merged**
